eureka:
  instance:
    instance-id: cityId

  client:
    service-url:
      defaultZone: http://localhost:9991/eureka/

server:
  port: 10010

spring:
  application:
    name: city
  cloud:
    config:
      server:
        git:
          uri: https://github.com/coding-technology/micro_config_rep.git