eureka:
  client:
    service-url:
      defaultZone: http://localhost:9991/eureka/,http://localhost:9992/eureka/,http://localhost:9993/eureka/
  instance:
    instance-id: city2Id

spring:
  application:
    name: city2
